version: "3.3"

services:
  api-rest-snet:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api-network
    image: api-rest-snet:1.0
    container_name: api-rest-container
    depends_on:
      - database
    ports:
      - 1323:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-config:/etc/postgresql

  database:
    build:
      context: .
      dockerfile: ./db-docker/Dockerfile
    networks:
      - api-network
    image: db-postgres:1.0
    container_name: database-container
    hostname: database
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=753159"
      - "POSTGRES_DB=api-rest-snet"
    ports:
      - 1324:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-config:/etc/postgresql
    entrypoint: docker-entrypoint.sh -c 'config_file=/etc/postgresql/postgresql.conf'

volumes:
  pg-data:
  pg-config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/postgres_custom"

networks:
  api-network:
    driver: bridge