openapi: 3.0.3

info:
  version: '1.0'
  title: API-REST-SNET
servers:
- url: http://localhost:4320
  description: Localhost
- url: https://virtserver.swaggerhub.com/patrickluan298/api-rest-snet/1.0
  description: SwaggerHub API
paths:
  /health-check:
    get:
      summary: Verifica a funcionalidade do serviço
      tags:
      - Health Check
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Aplicação rodando com sucesso
                  status:
                    type: string
                    example: OK
        404:
          description: Erro na funcionalidade do serviço
          content:
            application/json:
              example: "Not found"
  /NewEstablishment:
    post:
      summary: Cadastra um novo estabelecimento
      tags:
      - Establishments
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-Establishment"
        404:
          description: Erro ao cadastrar o estabelecimento
          content:
            application/json:
              example: "Not found"
  /GetEstablishment/{NumEstablishment}:
    parameters:
    - name: NumEstablishment
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Buscar um estabelecimento pelo seu número
      tags:
      - Establishments
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-Establishment"
        404:
          description: Número do estabelecimento não encontrado
          content:
            application/json:
              example: "Not found"
  /UpdateEstablishment/{NumEstablishment}:
    put:
      summary: Atualizar um estabelecimento
      tags:
        - Establishments
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-Establishment"
        404:
          description: Número do estabelecimento não encontrado
          content:
            application/json:
              example: "Not found"
  /GetAllEstablishments:
    get:
      summary: Buscar todos os estabelecimentos
      tags:
        - Establishments
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-allEstablishments"
  /DeleteEstablishment/{NumEstablishment}:
    delete:
      summary: Deletar um estabelecimento
      tags:
        - Establishments
      responses:
        200:
          description: Dados do estabelecimento
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-Establishment"
        404:
          description: Erros de validação
          content:
            application/json:
              example: "Not found"
  /NewStore:
    post:
      summary: Cadastra uma loja
      tags:
        - Stores
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-Store"
        404:
          description: Erro ao cadastrar o estabelecimento
          content:
            application/json:
              example: "Not found"
  /GetStore:
    get:
      summary: Buscar uma loja
      tags:
        - Stores
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-Store"
        404:
          description: Erro ao cadastrar o estabelecimento
          content:
            application/json:
              example: "Not found"
  /UpdateStore:
    put:
      summary: Atualizar uma loja
      tags:
        - Stores
      responses:
        200:
          description: Dados da loja
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-Store"
        404:
          description: Erro ao cadastrar o estabelecimento
          content:
            application/json:
              example: "Not found"
  /GetAllStores:
    get:
      summary: Buscar todas as lojas
      tags:
        - Stores
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-allStores"
  /DeleteStore:
    delete:
      summary: Deletar uma loja
      tags:
        - Stores
      responses:
        200:
          description: Dados da loja
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusOk-Store"
        404:
          description: Erro ao cadastrar o estabelecimento
          content:
            application/json:
              example: "Not found"
components:
  schemas:
    statusOk-Establishment:
      type: object
      properties:
        NumEstablishment:
          type: integer
        descricao:
          type: string
        status:
          type: string
          example: OK
    statusOk-allEstablishments:
      type: array
      items:
        $ref: "#/components/schemas/statusOk-Establishment"
    statusOk-Store:
      type: object
      properties:
        NumStore:
          type: integer
        descricao:
          type: string
        status:
          type: string
          example: OK
    statusOk-allStores:
      type: array
      items:
        $ref: "#/components/schemas/statusOk-Store"
  securitySchemes:
    auth:
      type: http
      scheme: bearer
